name: ORFS variables.yaml tester and linter

on:
  pull_request:

jobs:
  docs-test-job:
    name: 'Tests for variables.yaml'
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
        sparse-checkout: |
          flow/scripts/generate-variables-docs.py
          docs/user/FlowVariables.md
          yamlfix.toml
    - name: Run generate-variables-docs.py
      run: |
        python3 flow/scripts/generate-variables-docs.py
    - name: Check if FlowVariables.md is up to date
      run: |
        git diff --exit-code docs/user/FlowVariables.md
    - name: Install dependencies
      run: |
        python3 -m venv venv
        venv/bin/pip install --quiet yamlfix==1.17.0
    - name: Run yamlfix check
      run: |
        source venv/bin/activate
        yamlfix --version
        set -x
        yamlfix -c yamlfix.toml flow/scripts/variables.yaml
        git diff flow/scripts/variables.yaml
